get:
  operationId: get_pipeline_config_jepl
  summary: Gets JePL config configuration for the given pipeline.
  parameters:
    - in: path
      name: pipeline_id
      description: ID of the pipeline to get
      required: true
      schema:
        type: string
  description: >
    Returns the content of JePL's config file.
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                file_name:
                  type: string
                  example:
                    file_name: config.yml
                content:
                  type: object
                  $ref: '../components/schemas/CriterionBuild.yaml'
    '400':
      description: Invalid pipeline ID supplied
    '404':
      description: Pipeline not found
