openapi: 3.0.0
info:
  title: SQAaaS API
  description: >-
    API for the Software and Service Quality Assurance as a Service (SQAaaS)
    component.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.1.0
servers:
  - url: 'http://api.sqaaas.eosc-synergy.eu/v1'
    description: 'Optional server description, e.g. Main (production) server'
  - url: 'http://staging-api.sqaaas.eosc-synergy.eu'
    description: 'Optional server description, e.g. Internal staging server for testing'
paths:
  /pipeline:
    post:
      operationId: addPipeline
      summary: Creates a pipeline.
      description: >
        Provides a ready-to-use Jenkins pipeline based on the v2 series of
        jenkins-pipeline-library.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pipeline'
      responses:
        '201':
          description: Created
components:
  schemas:
    SQA_qc_style:
      type: object
    SQA_qc_coverage:
      type: object
    SQA_qc_functional:
      type: object
    SQA_qc_security:
      type: object
    SQA_qc_doc:
      type: object
    SQA_Criteria:
      type: array
      items:
        anyOf:
          - $ref: '#/components/schemas/SQA_qc_style'
          - $ref: '#/components/schemas/SQA_qc_coverage'
          - $ref: '#/components/schemas/SQA_qc_functional'
          - $ref: '#/components/schemas/SQA_qc_security'
          - $ref: '#/components/schemas/SQA_qc_doc'
    Pipeline:
      type: object
      properties:
        sqa_criteria:
          $ref: '#/components/schemas/SQA_Criteria'
        run:
          type: boolean
