type: object
description: Environment variables to be used at pipeline runtime
additionalProperties:
  type: string
example:
  JPL_IGNOREFAILURES: 'defined'
  JPL_DOCKERPUSH: 'docs service1 service4'
