type: object
description: Details about the composition of the services required for the pipeline execution
properties:
  version:
    type: string
    example: '3.7'
  services:
    type: object
    $ref: './ServiceDockerCompose.yaml'
