type: object
properties:
  id:
    type: string
    readOnly: true
    example: dd7d8481-81a3-407f-95f0-a2f1cb382a4b
  name:
    type: string
    format: '[A-Za-z0-9_.-]'
    example: sqaaas-api-spec
  config_data:
    type: array
    items:
      $ref: './JePL_config.yaml'
  composer_data:
    $ref: './JePL_composer.yaml'
  jenkinsfile_data:
    $ref: './JePL_jenkinsfile.yaml'
